### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Zeik0s** [Docbroke/WD_MyCloud#1]
Hi @Docbroke, 
could you provide some basic Documentation?

**Comment by Docbroke** [comment]
Look at this link
https://github.com/Johns-Q/wdmc-gen2

You may also find details in wd_mycloud forums

https://community.wd.com/t/mainline-kernel-4-11-x-for-wd-my-cloud-gen2/211143/10

**Comment by Zeik0s** [comment]
I already found these sites, but it would be really helpful for people that are looking for info if you could reference to these sites.
